#!/bin/bash
CHRONOS_HOME="/opt/chronos"
MESOS_HOME="/usr/share/java"
MESOS_LIB="/usr/local/lib/libmesos.so"
export JAVA_LIBPATH="/usr/local/lib"

# Chronos environment settings for start up
# Uncomment to customize your settings

# bind Chronos to specific port, otherwise random
# port between 30000-60000 is choosen
#export LIBPROCESS_PORT=5070

# change default log dir
#LOG_DIR="/var/log/chronos"

# Chronos storage
ZK_HOSTS="$(cat /etc/mesos/zk)"
#ZK_PATH=/chronos/state

# Chronos UI and declaration
#HOSTNAME=localhost
PORT=8080

# Mesos requirement
#MASTER=zk://localhost:2181/mesos
MASTER="$(cat /etc/mesos/zk)"
#USER=root
#CPU=0.1
#MEM=128
#DISK=256
#ROLE=*
#FW_NAME=chronos-2.0.1

# Use $OPTS to add other settings not handled by init script
#OPTS="--log_config /etc/chronos/logging.properties"

